master_host:
  children:
    master_hosts:
      hosts:
        ansible-home1:
          ansible_host: 51.250.91.141
    worker_hosts:
      hosts:
        ansible-home2:
          ansible_host: 84.201.128.22
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa